require("./connection");
const Member = require("./models/Member");
const Event = require("./models/Event");

function seedMembers() {
  Member.deleteMany({}, function (err) {
    if (err) console.log("Opps! Failed to delete members.");
    console.log("All Members deleted from db....");
  });
  const members = [
    {
      github: "https://github.com/Zanark",
      githubDP: "https://github.com/Zanark.png",
      linkedin: "https://www.linkedin.com/in/debashishzanark/",
      name: "Debashish Mishra",
      role: "alumni",
      skill: "Artificial Intelligence, Frontend, App Development",
      twitter: "https://twitter.com/zanark011",
    },
    {
      github: "https://github.com/SubhrajitPrusty",
      githubDP: "https://github.com/SubhrajitPrusty.png",
      linkedin: "https://www.linkedin.com/in/subhrajitprusty/",
      name: "Subrajit Prusty",
      role: "alumni",
      skill: "full-stack, AI",
      twitter: "https://twitter.com/subhrajit_",
    },
    {
      github: "https://github.com/kshitizranjan15",
      githubDP: "https://github.com/kshitizranjan15.png",
      linkedin: "https://www.linkedin.com/mwlite/in/kshitiz-ranjan-5452a9112",
      name: "KSHITIZ RANJAN",
      role: "member",
      skill: "Frontend",
      twitter: "@kshitizranjan15",
    },
    {
      github: "https://github.com/Ashutosh74554",
      githubDP: "https://github.com/Ashutosh74554.png",
      linkedin: "https://www.linkedin.com/mwlite/in/ashutosh-dash-1718a8208",
      name: "Ashutosh Dash",
      role: "member",
      skill: "App Development",
      twitter: "",
    },
    {
      github: "https://www.github.com/AyanDas348",
      githubDP: "https://www.github.com/AyanDas348.png",
      linkedin: "https://www.linkedin.com/in/ayan-das-0825a1121",
      name: "Ayan Das",
      role: "member",
      skill: "Machine Learning",
      twitter: "",
    },
    {
      github: "https://www.github.com/pritam047",
      githubDP: "https://www.github.com/pritam047.png",
      linkedin: "https://www.linkedin.com/in/pritam-kar-06b515176",
      name: "PRITAM KAR",
      role: "coordinator",
      skill: "Machine Learning, Backend, Frontend",
      twitter: "https://twitter.com/Pritam_kar13",
    },
    {
      github: "https://github.com/obli99",
      githubDP: "https://github.com/obli99.png",
      linkedin: "https://www.linkedin.com/in/jyoti-jayadeep-jena-9a4a5a184/",
      name: "Jyoti Jayadeep Jena",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/Subhodip11",
      githubDP: "https://github.com/Subhodip11.png",
      linkedin: "https://www.linkedin.com/in/subhodip-chatterjee-858098208",
      name: "Subhodip Chatterjee",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/Aakarsh05",
      githubDP: "https://github.com/Aakarsh05.png",
      linkedin: "https://www.linkedin.com/in/aakarsh-vatsraj-3525391b8/",
      name: "AAKARSH VATSRAJ",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/UtkarshShankar",
      githubDP: "https://github.com/UtkarshShankar.png",
      linkedin: "https://www.linkedin.com/in/utkarsh-shankar-963886212/",
      name: "Utkarsh Shankar",
      role: "member",
      skill: "App Development, UX / UI",
      twitter: "",
    },
    {
      github: "https://github.com/shivam248k",
      githubDP: "https://github.com/shivam248k.png",
      linkedin: "https://www.linkedin.com/in/shivam-kumar-sharma-56531b20b",
      name: "Shivam Kumar Sharma",
      role: "member",
      skill: "Artificial Intelligence, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/LoopGlitch26",
      githubDP: "https://github.com/LoopGlitch26.png",
      linkedin: "https://www.linkedin.com/in/bravish-ghosh/",
      name: "Bravish Ghosh",
      role: "coordinator",
      skill:
        "Machine Learning, Backend, Frontend, App Development, Blockchain, Cyber Security, IOT, Quantum Computing, DevOps, etc.",
      twitter: "",
    },
    {
      github: "https://github.com/Suvamrx",
      githubDP: "https://github.com/Suvamrx.png",
      linkedin: "https://www.linkedin.com/in/suvam-pattnaik-1771181a0",
      name: "Suvam Pattnaik",
      role: "member",
      skill: "Artificial Intelligence, Frontend, App Development",
      twitter: "",
    },
    {
      github: "https://github.com/iamAbhishekkumar",
      githubDP: "https://github.com/iamAbhishekkumar.png",
      linkedin: "https://www.linkedin.com/in/abhishek-kumar-531512176",
      name: "Abhishek Kumar",
      role: "member",
      skill: "Machine Learning, Backend, App Development",
      twitter: "",
    },
    {
      github: "https://github.com/Palak-Srivastava",
      githubDP: "https://github.com/Palak-Srivastava.png",
      linkedin: "https://www.linkedin.com/in/palak-srivastava",
      name: "Palak Srivastava",
      role: "member",
      skill: "Frontend, UX / UI, Cloud Architect",
      twitter: "Don't have",
    },
    {
      github: "https://github.com/Avinash-kumar-21",
      githubDP: "https://github.com/Avinash-kumar-21.png",
      linkedin: "https://www.linkedin.com/in/avinash-kumar-a56b33200",
      name: "Avinash Kumar",
      role: "member",
      skill: "Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/AbhinandanRoul",
      githubDP: "https://github.com/AbhinandanRoul.png",
      linkedin: "https://www.linkedin.com/in/abhinandanroul",
      name: "Abhinandan Roul",
      role: "member",
      skill: "Machine Learning, Artificial Intelligence, Backend",
      twitter: "",
    },
    {
      github: "https://github.com/shadaanhassan15",
      githubDP: "https://github.com/shadaanhassan15.png",
      linkedin: "https://www.linkedin.com/in/shadaan-hassan-667975189/",
      name: "Shadaan Hassan",
      role: "member",
      skill:
        "Machine Learning, Artificial Intelligence, Backend, Frontend, UX / UI",
      twitter: "https://twitter.com/shadaanhassan15",
    },
    {
      github: "https://github.com/monkas24x7",
      githubDP: "https://github.com/monkas24x7.png",
      linkedin: "https://www.linkedin.com/in/shubhanjan-dash-765944215/",
      name: "Shubhanjan Dash",
      role: "member",
      skill: "Machine Learning, Backend",
      twitter: "",
    },
    {
      github: "https://www.github.com/agarwalsahil0210",
      githubDP: "https://www.github.com/agarwalsahil0210.png",
      linkedin: "https://www.linkedin.com/in/agarwalsahil02",
      name: "Sahil Agarwal",
      role: "member",
      skill: "Frontend, App Development",
      twitter: "https://twitter.com/_agarwalsahil?s=09",
    },
    {
      github: "https://github.com/Tapas14102000",
      githubDP: "https://github.com/Tapas14102000.png",
      linkedin: "https://www.linkedin.com/in/tapas-sahu-b11932205",
      name: "Tapas Sahu",
      role: "member",
      skill: "Backend, Frontend, App Development",
      twitter: "",
    },
    {
      github: "https://github.com/debashishsamantara",
      githubDP: "https://github.com/debashishsamantara.png",
      linkedin: "https://www.linkedin.com/in/debashish-samantara",
      name: "Debashish Samantara",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/atulnarayan16",
      githubDP: "https://github.com/atulnarayan16.png",
      linkedin: "https://www.linkedin.com/in/atul-narayan-965a3b164/",
      name: "Atul Narayan",
      role: "member",
      skill: "Backend",
      twitter: "https://twitter.com/atul_narayan16",
    },
    {
      github: "https://github.com/amohapatra123",
      githubDP: "https://github.com/amohapatra123.png",
      linkedin: "https://www.linkedin.com/in/amohapatra123/",
      name: "Anshuman Mohapatra",
      role: "member",
      skill: "Machine Learning, Backend, Frontend",
      twitter: "https://twitter.com/nationofmyrules",
    },
    {
      github: "https://www.github.com/adarsh1405/",
      githubDP: "https://www.github.com/adarsh1405.png",
      linkedin: "https://www.linkedin.com/in/adarsh-padhi-64639217a/",
      name: "Adarsh Padhi",
      role: "coordinator",
      skill: "Machine Learning, Cyber Security",
      twitter: "https://twitter.com/adarsh_padhi",
    },
    {
      github: "https://github.com/ASVKVINAYAK",
      githubDP: "https://github.com/ASVKVINAYAK.png",
      linkedin: "https://www.linkedin.com/in/a-s-v-k-vinayak",
      name: "A S V K Vinayak",
      role: "member",
      skill: "Backend, App Development",
      twitter: "https://twitter.com/VinayakVirus",
    },
    {
      github: "https://github.com/imAdityaSatya",
      githubDP: "https://github.com/imAdityaSatya.png",
      linkedin: "https://www.linkedin.com/in/aditya-satya-55174b1a5",
      name: "Aditya Satya",
      role: "member",
      skill: "Just simple java coding so far",
      twitter: "",
    },
    {
      github: "https://github.com/abhishek622",
      githubDP: "https://github.com/abhishek622.png",
      linkedin: "https://www.linkedin.com/in/abhishek-prasad-00721918b/",
      name: "Abhishek Prasad",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/sumitt1080",
      githubDP: "https://github.com/sumitt1080.png",
      linkedin: "https://www.linkedin.com/in/sumit-thakur-7ba452191/",
      name: "Sumit Kumar Thakur",
      role: "member",
      skill: "Frontend, App Development, UX / UI",
      twitter: "https://twitter.com/SumitTh47464253",
    },
    {
      github: "https://github.com/Mona-1101",
      githubDP: "https://github.com/Mona-1101.png",
      linkedin: "https://www.linkedin.com/in/monalisha-sahoo-759b90200",
      name: "Monalisha Sahoo ",
      role: "member",
      skill: "Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/Jyo561",
      githubDP: "https://github.com/Jyo561.png",
      linkedin:
        "https://www.linkedin.com/mwlite/in/jyotiraditya-kuanar-8b39b7207",
      name: "Jyotiraditya Kuanar",
      role: "member",
      skill: "Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/RIJULDAS",
      githubDP: "https://github.com/RIJULDAS.png",
      linkedin: "https://www.linkedin.com/in/sri-rijul-das-028aa419b",
      name: "SRI RIJUL DAS",
      role: "member",
      skill: "Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/swetasahoo29",
      githubDP: "https://github.com/swetasahoo29.png",
      linkedin: "https://www.linkedin.com/in/sweta-sahoo-ab2228192",
      name: "Sweta Snigdha Sahoo",
      role: "member",
      skill: "Backend, Frontend, UX / UI",
      twitter: "Com",
    },
    {
      github: "https://github.com/HarshSinha18",
      githubDP: "https://github.com/HarshSinha18.png",
      linkedin: "https://www.linkedin.com/in/harsh-sinha-952892199",
      name: "Harsh Sinha",
      role: "member",
      skill: "Frontend",
      twitter: "https://mobile.twitter.com/harsh_sinha__18",
    },
    {
      github: "https://github.com/satyabrata-mishra",
      githubDP: "https://github.com/satyabrata-mishra.png",
      linkedin: "https://www.linkedin.com/in/satyabrata-mishra-52ab58218",
      name: "Satyabrata Mishra",
      role: "member",
      skill: "App Development",
      twitter: "",
    },
    {
      github: "https://github.com/Pranjali912",
      githubDP: "https://github.com/Pranjali912.png",
      linkedin: "https://www.linkedin.com/in/pranjali-b60a22215/",
      name: "Pranjali",
      role: "member",
      skill: "Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/sambitpal2002",
      githubDP: "https://github.com/sambitpal2002.png",
      linkedin: "https://www.linkedin.com/in/sspal02/",
      name: "SAMBIT SOURAV PAL",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/Ashis-007",
      githubDP: "https://github.com/Ashis-007.png",
      linkedin: "https://www.linkedin.com/in/subhransu-dash",
      name: "Subhransu Dash",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/Kaphleamrit",
      githubDP: "https://github.com/Kaphleamrit.png",
      linkedin: "https://www.linkedin.com/in/amrit-kaphle-4948aa194",
      name: "Amrit Kafle",
      role: "member",
      skill: "Backend, Frontend, App Development",
      twitter: "https://twitter.com/kaphley1?s=09",
    },
    {
      github: "https://github.com/pnkr01",
      githubDP: "https://github.com/pnkr01.png",
      linkedin: "https://www.linkedin.com/in/pawan-k-9490581b5/",
      name: "Pawan Kumar",
      role: "member",
      skill: "Frontend, Learning App Development and doing CP",
      twitter: "",
    },
    {
      github: "https://github.com/lipsamishra1609",
      githubDP: "https://github.com/lipsamishra1609.png",
      linkedin: "https://www.linkedin.com/in/lipsa-mishra-a834aa1a4/",
      name: "Lipsa Mishra",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/ishivamgupta9",
      githubDP: "https://github.com/ishivamgupta9.png",
      linkedin: "https://www.linkedin.com/in/shivam-gupta-20",
      name: "Shivam Gupta",
      role: "member",
      skill: "Frontend, App Development, Java,Kotlin,Python,SQL",
      twitter: "Ishivamgupta_",
    },
    {
      github: "https://github.com/majjikishore007",
      githubDP: "https://github.com/majjikishore007.png",
      linkedin: "http://linkedin.com/in/majji-kishore-ab18a9195",
      name: "Majji Kishore",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "MajjiKishore1",
    },
    {
      github: "https://github.com/MINALRAI",
      githubDP: "https://github.com/MINALRAI.png",
      linkedin: "www.linkedin.com/in/minal-rai",
      name: "Minal Rai",
      role: "member",
      skill: "Frontend, UX / UI",
      twitter: "",
    },
    {
      github: "https://github.com/SatyapragyanDas",
      githubDP: "https://github.com/SatyapragyanDas.png",
      linkedin: "https://www.linkedin.com/in/satyapragyan-das-50b336122/",
      name: "Satyapragyan Das",
      role: "member",
      skill: "Machine Learning, Artificial Intelligence",
      twitter: "https://twitter.com/SatyapragyanDas",
    },
    {
      github: "https://github.com/Shuwani",
      githubDP: "https://github.com/Shuwani.png",
      linkedin: "https://www.linkedin.com/mwlite/in/shuwani-a578bb1aa",
      name: "Shuwani",
      role: "member",
      skill: "Machine Learning, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/himanshu251001",
      githubDP: "https://github.com/himanshu251001.png",
      linkedin: "https://www.linkedin.com/in/himanshu-mishra-92048a203",
      name: "HIMANSHU MISHRA",
      role: "member",
      skill: "Frontend",
      twitter: "Mr_Mishra_11",
    },
    {
      github: "https://github.com/Rishika6",
      githubDP: "https://github.com/Rishika6.png",
      linkedin: "https://www.linkedin.com/in/rishika-wadhera-931588199/",
      name: "Rishika Wadhera",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://www.github.com/itsjohnty",
      githubDP: "https://www.github.com/itsjohnty.png",
      linkedin: "https://www.linkedin.com/in/aditya-sharma-9bb954199",
      name: "Aditya Sharma",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/RiturajGupta21",
      githubDP: "https://github.com/RiturajGupta21.png",
      linkedin: "https://www.linkedin.com/in/rituraj-gupta",
      name: "Rituraj Gupta",
      role: "member",
      skill: "Machine Learning, Backend, Frontend, App Development",
      twitter: "https://twitter.com/guptarituraj01?s=09",
    },
    {
      github: "https://github.com/Satyajit99p",
      githubDP: "https://github.com/Satyajit99p.png",
      linkedin: "https://www.linkedin.com/in/satyajit-panigrahi-b7a425202/",
      name: "Satyajit Panigrahi",
      role: "member",
      skill: "Machine Learning, Artificial Intelligence, Data Science",
      twitter: "",
    },
    {
      github: "https://www.github.com/skpandey885",
      githubDP: "https://www.github.com/skpandey885.png",
      linkedin: "https://www.linkedin.com/in/skpandey885",
      name: "Sachin Kumar Pandey ",
      role: "member",
      skill: "Frontend, UX / UI, iOS Development ",
      twitter: "https://www.twitter.com/iamsachin_47",
    },
    {
      github: "http://www.github.com/Suraj-Kumar-Mohanty",
      githubDP: "http://www.github.com/Suraj-Kumar-Mohanty.png",
      linkedin: "http://www.linkedin.com/in/surajkumarmohanty",
      name: "Suraj Kumar Mohanty",
      role: "member",
      skill: "App Development",
      twitter: "",
    },
    {
      github: "https://github.com/sid-mr-im",
      githubDP: "https://github.com/sid-mr-im.png",
      linkedin: "https://www.linkedin.com/in/siddhant-sarthak/",
      name: "Siddhant Sarthak",
      role: "member",
      skill:
        "Machine Learning, Backend, Frontend, App Development, Cyber Security, UX / UI, IOT",
      twitter: "https://twitter.com/sid_mr_im",
    },
    {
      github: "https://github.com/sayantan-here",
      githubDP: "https://github.com/sayantan-here.png",
      linkedin: "https://www.linkedin.com/in/sayantan-das-ab7798218",
      name: "Sayantan Das",
      role: "member",
      skill: "Backend",
      twitter: "",
    },
    {
      github: "https://github.com/Raviruler",
      githubDP: "https://github.com/Raviruler.png",
      linkedin: "https://www.linkedin.com/in/ravi-kumar-prasad-16b1881ba",
      name: "RAVI KUMAR PRASAD",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/opticalD",
      githubDP: "https://github.com/opticalD.png",
      linkedin: "https://www.linkedin.com/in/shubhranshu-pattanaik-116099219",
      name: "Shubhranshu pattanaik",
      role: "member",
      skill: "App Development, Cyber Security",
      twitter: "",
    },
    {
      github: "https://github.com/SoubhagyaKumaNayak",
      githubDP: "https://github.com/SoubhagyaKumaNayak.png",
      linkedin:
        "https://www.linkedin.com/mwlite/in/soubhagya-kumar-nayak-711370208",
      name: "Soubhagya Kumar Nayak",
      role: "member",
      skill: "App Development",
      twitter: "",
    },
    {
      github: "https://github.com/Alik-Kumar-Ghosh",
      githubDP: "https://github.com/Alik-Kumar-Ghosh.png",
      linkedin: "https://www.linkedin.com/in/alik-kumar-ghosh-9638571a6",
      name: "Alik Kumar Ghosh",
      role: "member",
      skill: "Frontend, App Development, UX / UI",
      twitter: "",
    },
    {
      github: "https://github.com/sudhir-120901",
      githubDP: "https://github.com/sudhir-120901.png",
      linkedin: "https://www.linkedin.com/in/sudhir-narayan-nanda-56b629203/",
      name: "Sudhir Narayan Nanda",
      role: "member",
      skill: "Frontend",
      twitter: "https://twitter.com/Sudhir23538843",
    },
    {
      github: "https://github.com/sakshi1512kri",
      githubDP: "https://github.com/sakshi1512kri.png",
      linkedin: "https://www.linkedin.com/in/sakshi-kumari-78bb46207",
      name: "Sakshi Kumari",
      role: "member",
      skill: "Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/siddhant2002",
      githubDP: "https://github.com/siddhant2002.png",
      linkedin:
        "https://www.linkedin.com/in/siddhant-swarup-mallick-b5b79a1bb/",
      name: "Siddhant Swarup Mallick",
      role: "member",
      skill: "Competative coding",
      twitter: "https://twitter.com/SwarupSiddhant",
    },
    {
      github: "https://github.com/elina-29",
      githubDP: "https://github.com/elina-29.png",
      linkedin: "https://www.linkedin.com/in/pakhi-sarkar-b0674b203/",
      name: "Pakhi Sarkar",
      role: "member",
      skill: "Frontend",
      twitter: "https://twitter.com/pakhi1707",
    },
    {
      github: "https://github.com/rokkam7784",
      githubDP: "https://github.com/rokkam7784.png",
      linkedin: "https://www.linkedin.com/in/r-vinayak-30165a1b0/",
      name: "R . Vinayak",
      role: "member",
      skill: "Machine Learning, App Development, Arduino",
      twitter: "",
    },
    {
      github: "https://github.com/Kumar2390",
      githubDP: "https://github.com/Kumar2390.png",
      linkedin: "https://www.linkedin.com/in/ashwini-kumar-behera-14a9a4215/",
      name: "Ashwini kumar Behera",
      role: "member",
      skill: "Machine Learning, Frontend",
      twitter: "https://twitter.com/KumarAs46674624",
    },
    {
      github: "https://github.com/DP-0P",
      githubDP: "https://github.com/DP-0P.png",
      linkedin: "https://www.linkedin.com/in/deepak-pattnayak-49534015b/",
      name: "Deepak Pattnayak ",
      role: "member",
      skill: "Backend, Frontend, App Development",
      twitter: "DP02998464",
    },
    {
      github: "https://github.com/SuvojitBarick",
      githubDP: "https://github.com/SuvojitBarick.png",
      linkedin: "https://www.linkedin.com/in/suvojitbarick",
      name: "Suvojit Barick",
      role: "member",
      skill: "Machine Learning",
      twitter: "",
    },
    {
      github: "https://github.com/amitosh2578",
      githubDP: "https://github.com/amitosh2578.png",
      linkedin: "https://www.linkedin.com/in/amitosh-mohapatra-477a97213/",
      name: "Amitosh Mohapatra",
      role: "member",
      skill: "IOT",
      twitter: "",
    },
    {
      github: "https://github.com/Prakashpathak984",
      githubDP: "https://github.com/Prakashpathak984.png",
      linkedin: "https://www.linkedin.com/in/prakash-pathak-699895201",
      name: "Prakash Pathak",
      role: "member",
      skill: "Machine Learning, Backend, App Development, Cyber Security",
      twitter: "",
    },
    {
      github: "https://github.com/Shivangibose",
      githubDP: "https://github.com/Shivangibose.png",
      linkedin: "https://www.linkedin.com/in/shivangi-bose-856b56202/",
      name: "SHIVANGI BOSE",
      role: "member",
      skill: "Frontend",
      twitter: "https://twitter.com/BoseShivangi",
    },
    {
      github: "https://github.com/sabyasachee20",
      githubDP: "https://github.com/sabyasachee20.png",
      linkedin: "https://www.linkedin.com/in/sabyasachee-mohapatra-568ba8218/",
      name: "Sabyasachee Mohapatra",
      role: "member",
      skill: "Backend, Frontend, Java",
      twitter: "",
    },
    {
      github: "https://github.com/Sudeep25022000",
      githubDP: "https://github.com/Sudeep25022000.png",
      linkedin: "https://www.linkedin.com/in/sudeepswain2502",
      name: "Sudeep Swain",
      role: "member",
      skill:
        "Machine Learning, Artificial Intelligence, Backend, Frontend, Cyber Security, IOT",
      twitter: "https://mobile.twitter.com/SudeepSwain25",
    },
    {
      github: "https://github.com/Ishaandeep",
      githubDP: "https://github.com/Ishaandeep.png",
      linkedin: "https://www.linkedin.com/in/ishaan-deep-6294361ba/",
      name: "Ishaan Deep",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "https://twitter.com/ishaan_5deep",
    },
    {
      github: "https://github.com/subham73",
      githubDP: "https://github.com/subham73.png",
      linkedin: "https://www.linkedin.com/in/subham-jyoti-a2352a213",
      name: "Subham Jyoti",
      role: "member",
      skill: "Machine Learning, Simulation,CP",
      twitter: "subh_ham73",
    },
    {
      github: "https://github.com/vaishnavikhushi14",
      githubDP: "https://github.com/vaishnavikhushi14.png",
      linkedin: "https://www.linkedin.com/in/vaishnavi-khushi-44329b219",
      name: "Vaishnavi Khushi ",
      role: "member",
      skill: "App Development",
      twitter: "",
    },
    {
      github: "https://github.com/dibyant",
      githubDP: "https://github.com/dibyant.png",
      linkedin: "https://www.linkedin.com/in/dibyant-patro-0518931b8/",
      name: "T.Dibyanta patro",
      role: "member",
      skill: "App Development",
      twitter: "",
    },
    {
      github: "https://github.com/SumanMore",
      githubDP: "https://github.com/SumanMore.png",
      linkedin: "https://www.linkedin.com/in/suman-more-5937aa1b0/",
      name: "Suman More",
      role: "member",
      skill: "Backend, Frontend",
      twitter: "",
    },
    {
      github: "https://github.com/demo",
      githubDP: "https://github.com/demo.png",
      linkedin: "",
      name: "Nikunjan Bihari Kar",
      role: "teacher",
      skill: "Artificial Intelligence, Frontend, App Development",
      twitter: "",
    },
    {
      github:"https://github.com/Parag357",
      githubDP:"https://github.com/Parag357.png",
      linkedin:"https://www.linkedin.com/in/parag-bhattacharjee-905196179/",
      name:"Parag Bhattacharjee",
      role:"alumni",
      skill:"Backend, Frontend, Dev-ops",
      twitter:""
    }
  ];
  Member.insertMany(members, function (err) {
    if (err) console.log("Opps! Failed to insert to db.");
    console.log("Yay! Done inserting members.");
  });
}

function seedEvents() {
  Event.deleteMany({}, function (err) {
    if (err) console.log("Opps! Failed to delete events.");
    console.log("All Events deleted from db....");
  });
  const events = [
    {
      name: "HackCodex",
      link: "https://hackodex.codex-iter.in/",
      description:
        "Hackodex is an Open-source contribution festival organized by Codex Club (The official Coding club of ITER, SOA). This month-long event will take place in the month of April where people from various field of expertise come together to share their experiences to the budding coders. It Focuses on the development of pre-existing or new projects that are hosted by the project mentors of ITER.",
      images: [
        "https://firebasestorage.googleapis.com/v0/b/codex-website-6a27d.appspot.com/o/b316e0bda36bbcd06c51cb5c317e863429e6540c.jpeg?alt=media&token=45a6e19d-0437-40fe-9a8a-fe422ba7986e",
        "https://firebasestorage.googleapis.com/v0/b/codex-website-6a27d.appspot.com/o/3e170696ee8bcc26ecb1c967adddaa3b728a427a.jpeg?alt=media&token=2328b0ec-3c49-42ee-ba52-e1a74d1c9d2f",
        "https://firebasestorage.googleapis.com/v0/b/codex-website-6a27d.appspot.com/o/b693956cdea637352c418142c957574f67f84e4c.jpeg?alt=media&token=40d60907-6190-45f1-814a-be82b8adab33",
      ],
      organizers: ["Codex-ITER"],
      status: "past",
    },
  ];
  Event.insertMany(events, function (err) {
    if (err) console.log("Opps! Failed to insert events.");
    console.log("Yay! Done inserting events.");
  });
  // Events.find({}, function (err, res) {
  //   if (err) console.log("Opps! Failed to get events.");
  //   console.log(res);
  // });
}

seedMembers();
seedEvents();
